### ISSUE TITLE
3.5.1 ? 

### ISSUE THREAD

**Issue by niccolox** [mlutfy/hosting_wordpress#21]
hi

does hosting_wordpress work with Aegir 3.5.1 ? 

I am trying to apply patches but the target code structure seems to have changed

https://github.com/mlutfy/hosting_wordpress/blob/7.x-3.x/patches/provision.patch

targets a file that no longer exists? or has been moved? http/Provision/Service/http/public.php

http://cgit.drupalcode.org/provision/tree/Provision/Service
http://cgit.drupalcode.org/provision/tree/Provision/Service/null.php

**Comment by mlutfy** [comment]
hi!

That patch should not be necessary anymore (in the latest git master branch of hosting_wordpress).

For what it's worth, I don't know for Aegir 3.5, but in 3.6 this exists:
http://cgit.drupalcode.org/provision/tree/http/Provision/Service/http/public.php?h=7.x-3.6
