### ISSUE TITLE
Installation on BOA-3.2.1

### ISSUE THREAD

**Issue by Monsoonpk** [mlutfy/hosting_wordpress#24]
I have BOA-3.2.1 (https://github.com/omega8cc/boa) hosted on my own server. I want to know if installation process is same for BOA-3.2.1? And is it compatible with it? 
Your input will help a lot. Thanks.

**Comment by mlutfy** [comment]
It should be compatible, but keep in mind that the module is experimental and incomplete. I use it in production, but it mostly just installs WordPress, configures the vhost and has some drush/wp-cli integration. It does not configure cron, manage https, backup/restore, etc.

Of course, your feedback, patches, support are more than welcome.
