### ISSUE TITLE
Restore from Drupal backup failed - Call to undefined function hosting_wpsite_get_backup() in drush_hosting_wpsite_pre_hosting_task()

### ISSUE THREAD

**Issue by socialnicheguru** [mlutfy/hosting_wordpress#25]
Ran task to restore a Drupal site from a backup
It failed with the following error:

WD php: Error: Call to undefined function hosting_wpsite_get_backup() in drush_hosting_wpsite_pre_hosting_task() (line 85 of /var/aegir/hostmaster-7.x-3.x-2018-08-08-0255/sites/mysite/modules/hosting_wordpress/hosting_wpsite/hosting_wpsite.drush.inc). | - | error
-- | -- | --
Drush command terminated abnormally due to an unrecoverable error.

**Comment by mlutfy** [comment]
We must have encountered this pretty much at the same time. I pushed a fix/workaround in the 7.x-3.x branch: https://github.com/mlutfy/hosting_wordpress/commit/0896569b8b65ec8f8e6e0a807fbeaa0d8718d0bc
