### ISSUE TITLE
Got this working !

### ISSUE THREAD

**Issue by devekko** [mlutfy/hosting_wordpress#9]
hi

finally got around to hacking my way to Aegir Wordpress victory

bunch of issues, which I will need to circle back to record properly

this is a meta issue
1. had to comment out error log in apache config for wordpress site and restart apache, for some reason it didnt work
# PROVISION_LOGS
# ==============
# Set error log to site-specific file.
# ErrorLog /var/log/aegir/wp2.arizmendix.devekko.net.error.log
# ==============
1. wpsite form complained about languages

Notice: Undefined variable: selected_profile in hosting_wpsite_form() (line 300 of /var/aegir/hostmaster-7.x-3.1/sites/all/modules/hosting_wordpress/hosting_wpsite/hosting_wpsite.form.inc).
1. wp cli doesnt seem to work as well as drush 

aegir@arix:~/platforms/wordpress-core/sites$ wp
PHP Notice:  Undefined index: db_name in /var/aegir/.composer/vendor/wp-cli/wp-cli/php/wp-cli.php(23) : eval()'d code on line 18
PHP Notice:  Undefined index: db_user in /var/aegir/.composer/vendor/wp-cli/wp-cli/php/wp-cli.php(23) : eval()'d code on line 21
PHP Notice:  Undefined index: db_passwd in /var/aegir/.composer/vendor/wp-cli/wp-cli/php/wp-cli.php(23) : eval()'d code on line 24
PHP Notice:  Undefined index: db_host in /var/aegir/.composer/vendor/wp-cli/wp-cli/php/wp-cli.php(23) : eval()'d code on line 27
PHP Notice:  Undefined index: wp_content_dir in /var/aegir/.composer/vendor/wp-cli/wp-cli/php/wp-cli.php(23) : eval()'d code on line 30
Error: 

<h1>Error establishing a database connection</h1>

<p>This either means that the username and password information in your <code>wp-config.php</code> file is incorrect or we can't contact the database server at <code></code>. This could mean your host's database server is down.</p>

<ul>
        <li>Are you sure you have the correct username and password?</li>
        <li>Are you sure that you have typed the correct hostname?</li>
        <li>Are you sure that the database server is running?</li>
</ul>

<p>If you're unsure what these terms mean you should probably contact your host. If you still need help you can always visit the <a href='https://wordpress.org/support/'>WordPress Support Forums</a>.</p>

1. need to update or create views and menu items to be non specific to Drupal or maybe create a Wordpress section
2. Site and Site in Content Types (need to make that Drupal Site and Wordpress Site) update, couldnt see how to make Views display Wpplatform and wpsite... I guess that needs to be done in code and then in the View
3. symlink for composer install of wp-cli was wrong on trusty

anyways.. great

**Comment by mlutfy** [comment]
Hi Nicholas, thanks for the tests/feedback!
- on the Apache log, did you have a specific error? You mention provision_log, is that a contrib module?
- to use 'wp', you have to use 'drush wp [...]'. This loads the db settings from the drush config.
- Error establishing a database connection: was this on the command line, or when visiting the site in http?

**Comment by devekko** [comment]
closing, see my other tickets
